---
##This only creates an EC2 and nothing else
# - name: Create EC2
#   hosts: localhost
#   vars_files: 
#     - vault.yaml
#   roles:
#     - aws

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  vars_files:
    - vault.yaml
  roles:
    - configure
#    - RedHatOfficial.rhel8_stig